allowed-origins: "https://mycoffee.vercel.app,https://mycoffee-*.vercel.app"

logging:
    level:
        org:
            hibernate: error
            springframework.core: error
            springframework.web: error
        root: error
